name: IPTV All

on:
  schedule:
    - cron: "0 9 * * *" # 每天 UTC 上午 9 点运行
  workflow_dispatch:
    inputs:
      reason:
        description: '手动触发的原因'
        required: false
        default: '手动执行'

run-name: IPTV 自动更新运行

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest
      volumes:
        - ${{ github.workspace }}:/__w/your_repo
      options: --user root # 以 root 用户运行容器，解决权限问题

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 调试文件系统
        run: |
          ls -la /__w/your_repo
          whoami
          id -u
        working-directory: /__w/your_repo

      - name: 配置 Git
        run: |
          git config --global --add safe.directory /__w/your_repo
          git config --global user.email "mmgg3381@gmail.com"
          git config --global user.name "aayyy99"
          git checkout ${{ github.ref }}
        working-directory: /__w/your_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装 Python 依赖
        run: pip install selenium requests

      - name: 等待 Selenium Hub 启动并就绪
        run: |
          echo "等待 Selenium Hub 在 localhost:4444 上启动..."
          until curl -s http://localhost:4444/wd/hub/status | grep '"ready": true' > /dev/null; do
            echo "Selenium Hub 尚未就绪，等待 5 秒..."
            sleep 5
          done
          echo "Selenium Hub 已就绪！"
        timeout-minutes: 5

      - name: 运行直播源获取脚本
        run: python /__w/your_repo/get_tv_livestream.py
        working-directory: /__w/your_repo

      - name: 清理旧的生成文件
        run: |
          echo "开始清理旧的 .txt 文件..."
          rm -f IPTV.txt
          rm -f hebei.txt beijing.txt guangdong.txt shanghai.txt tianjin.txt chongqing.txt shanxi.txt shaanxi.txt liaoning.txt jiangsu.txt zhejiang.txt anhui.txt fujian.txt jiangxi.txt shandong.txt henan.txt hubei.txt hunan.txt
          rm -f shodan_general_iptv.txt zoomeye_general_iptv.txt
          rm -rf downloads/
          echo "旧文件清理完成。"
        working-directory: /__w/your_repo

      - name: 提交并推送更改
        run: |
          git add combined_livestreams.txt || echo "没有 combined_livestreams.txt 文件需要添加"
          git commit -m "更新合并后的电视直播源并清理旧文件" || echo "没有新的更改需要提交"
          git push
        working-directory: /__w/your_repo
