name: IPTV All
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 卸载系统自带 Chrome（避免高版本干扰）
        run: |
          sudo apt-get remove -y google-chrome-stable || true
          sudo apt-get autoremove -y

      - name: 安装指定旧版 Chrome（126.0.6478.127）
        run: |
          wget https://ftp.slimjetbrowser.com/chrome/linux/126.0.6478.127/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          rm google-chrome-stable_current_amd64.deb

      - name: 查看Chrome版本（调试用）
        run: google-chrome --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install selenium requests

      - name: 自动安装匹配版本 ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          echo "当前Chrome主版本：$CHROME_VERSION"
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          echo "获取到的ChromeDriver版本：$DRIVER_VERSION"
          wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
          sudo chmod +x /usr/local/bin/chromedriver

      - name: 运行脚本
        run: python ${{ github.workspace }}/IPTV.py

      - name: 提交并推送更改
        run: |
          git config --local user.email "mmgg3381@gmail.com"
          git config --local user.name "aayyy99"
          git add *.txt
          git commit -m "Add generated file" || echo "No changes to commit"
          git push
