name: IPTV All

on:
  # push: # 已注释掉，不会在每次推送时运行
  schedule:
    - cron: "0 9 * * *" # 每天 UTC 上午 9 点运行
  workflow_dispatch: # 添加手动触发事件
    inputs:
      reason:
        description: '手动触发的原因'
        required: false
        default: '手动执行'
jobs:
  build:
    runs-on: ubuntu-latest # Using the default GitHub Actions runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install selenium requests

      - name: 运行脚本
        run: python ${{ github.workspace }}/IPTV.py

      - name: 提交并推送更改
        run: |
          git config --local user.email "mmgg3381@gmail.com"
          git config --local user.name "aayyy99"
          git add *.txt
          git commit -m "Add generated file" || echo "No changes to commit"
          git push
