name: IPTV All
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install selenium requests

      - name: Download latest ChromeDriver
        run: |
          CHROME_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json | grep -oP '"build":\s*"\K[0-9.]+' | head -1)
          wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python ${{ github.workspace }}/IPTV.py

      - name: Commit and push changes
        run: |
          git config --local user.email "mmgg3381@gmail.com"
          git config --local user.name "aayyy99"
          git add *.txt
          git commit -m "Add generated file" || echo "No changes to commit"
          git push
