name: IPTV All
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install selenium requests

      - name: 自动下载最新版 ChromeDriver
        run: |
          # 获取最新版 chromedriver 版本号
          LATEST_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
          sudo chmod +x /usr/local/bin/chromedriver

      - name: 运行脚本
        run: python ${{ github.workspace }}/IPTV.py

      - name: 提交并推送更改
        run: |
          git config --local user.email "mmgg3381@gmail.com"
          git config --local user.name "aayyy99"
          git add *.txt
          git commit -m "Add generated file" || echo "No changes to commit"
          git push
