name: IPTV All
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome:114.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install selenium requests

      - name: 运行脚本
        run: python ${{ github.workspace }}/IPTV.py

      - name: 提交并推送更改
        run: |
          git config --local user.email "mmgg3381@gmail.com"
          git config --local user.name "aayyy99"
          git add *.txt
          git commit -m "Add generated file" || echo "No changes to commit"
          git push
