name: IPTV 直播源抓取

on:
  schedule:
    - cro: "0 9 * * *" # 每天 UTC 上午 9 点运行
  workflow_dispatch:
    inputs:
      reason:
        description: '手动触发原因'
        required: false
        default: '手动运行'

run-name: IPTV 抓取 - ${{ github.event.inputs.reason || github.run_id }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 调试仓库
        run: |
          echo "工作目录: ${{ github.workspace }}"
          ls -la ${{ github.workspace }}
          if [ -d ${{ github.workspace }}/.git ]; then
            echo "Git 仓库存在"
            git status
          else
            echo "Git 仓库不存在"
            exit 1
          fi
          if [ -f ${{ github.workspace }}/get_tv_livestream.py ]; then
            echo "抓取脚本存在"
          else
            echo "抓取脚本不存在"
            exit 1
          fi

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装 Chrome 和 Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          # 安装 Chrome
          curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # 安装 Chromedriver
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: 安装 Python 依赖
        run: |
          pip install --no-cache-dir -r ${{ github.workspace }}/requirements.txt

      - name: 运行抓取脚本
        run: python ${{ github.workspace }}/get_tv_livestream.py

      - name: 提交并推送结果
        run: |
          git config user.email "mmgg3381@gmail.com"
          git config user.name "aayyy99"
          git add combined_livestreams.txt || echo "没有 combined_livestreams.txt 文件"
          git commit -m "更新直播源" || echo "没有更改需要提交"
          git push
