name: IPTV Web Scraper

on:
  schedule:
    - cron: "0 9 * * *" # 每天 UTC 上午 9 点运行
  workflow_dispatch:
    inputs:
      reason:
        description: '手动触发的原因'
        required: false
        default: '手动执行'

run-name: IPTV 自动抓取运行 - ${{ github.event.inputs.reason || github.run_id }}

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:126.0.6478.126 # 固定版本
      volumes:
        - ${{ github.workspace }}:/__w/your_repo
      options: --user root --shm-size=2g # 以 root 用户运行，增加共享内存

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          path: /__w/your_repo # 明确检出到挂载路径

      - name: 安装 Git
        run: |
          apt-get update
          apt-get install -y git
          git --version
        working-directory: /__w/your_repo

      - name: 调试 Git 仓库和文件系统
        run: |
          ls -la /__w/your_repo
          if [ -d /__w/your_repo/.git ]; then
            echo "Git 仓库存在"
            git status
          else
            echo "Git 仓库不存在"
            exit 1
          fi
          if [ -f /__w/your_repo/get_tv_livestream.py ]; then
            echo "抓取脚本存在"
          else
            echo "抓取脚本不存在"
            exit 1
          fi
          whoami
          id -u
        working-directory: /__w/your_repo

      - name: 配置 Git
        run: |
          git config --global --add safe.directory /__w/your_repo
          git config --global user.email "mmgg3381@gmail.com"
          git config --global user.name "aayyy99"
        working-directory: /__w/your_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # 指定具体 Python 版本

      - name: 安装 Python 依赖
        run: |
          pip install --no-cache-dir -r /__w/your_repo/requirements.txt
        working-directory: /__w/your_repo

      - name: 等待 Selenium Hub 启动
        run: |
          echo "等待 Selenium Hub 在 localhost:4444 上启动..."
          until curl -s http://localhost:4444/wd/hub/status | grep '"ready": true' > /dev/null; do
            echo "Selenium Hub 尚未就绪，等待 5 秒..."
            sleep 5
          done
          echo "Selenium Hub 已就绪！"
        timeout-minutes: 5
        working-directory: /__w/your_repo

      - name: 运行抓取脚本
        run: python /__w/your_repo/get_tv_livestream.py
        working-directory: /__w/your_repo

      - name: 清理旧文件
        run: |
          echo "开始清理旧的 .txt 文件..."
          rm -f /__w/your_repo/*.txt
          rm -rf /__w/your_repo/downloads/
          echo "旧文件清理完成。"
        working-directory: /__w/your_repo

      - name: 提交并推送更改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add combined_livestreams.txt || echo "没有 combined_livestreams.txt 文件需要添加"
          git commit -m "更新抓取的电视直播源并清理旧文件" || echo "没有新的更改需要提交"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        working-directory: /__w/your_repo
